services:
  picroscope-videostream:
    build: .
    container_name: tinc-livestream-rpi-side
    # privileged: true
    ports:
      - "700:700/tcp"
      - "700:700/udp"
      - "8888:8888"
        #network_mode: host
    volumes:
     # - ./tinc:/public/home/pvbaudin/tinc/tinc
      - ./scripts:/scripts
      - ./tinc:/etc/tinc
        # - ./nginx-stuff/default.conf:/etc/nginx/http.d/default.conf
      - ./nginx-stuff/nginx.conf:/etc/nginx/nginx.conf
      - /var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
      - ./scripts/remake-default-conf.sh:/etc/periodic/daily/remake-default-conf
     # usernames and passwords
      - ./nginx-stuff/.htpasswd:/etc/nginx/.htpasswd
    environment:
       #- IP_ADDR=128.114.198.51
       - IP_ADDR=10.20.30.4
       - ADDRESS=10.20.30.4
       - NETMASK=255.255.255.0
       - NETWORK=10.20.30.0/24
       - RUNMODE=evee
    
    devices:
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
 #  dns: 192.168.1.154
    restart: always
